version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # Login to ECR
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 045615334997.dkr.ecr.us-east-2.amazonaws.com
      # Set repository URI and image tag
      - REPOSITORY_URI=045615334997.dkr.ecr.us-east-2.amazonaws.com/ai-reciepe-finder-docker-snaps
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to ECR repository...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      # your ECS container name
      - DOCKER_CONTAINER_NAME=ai-recipe-finder-container
      - printf '[{"name":"ai-recipe-finder-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Container name is $DOCKER_CONTAINER_NAME
      - echo Printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json