version: 0.2
phases:
  pre_build:
    commands:
      - echo "PRE-BUILD PHASE STARTED"
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 045615334997.dkr.ecr.us-west-2.amazonaws.com
      - export AWS_DEFAULT_REGION=us-west-2
      - export AWS_REGION=us-west-2
      - REPOSITORY_URI=045615334997.dkr.ecr.us-west-2.amazonaws.com/recipe-finder-prod
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      # DEBUG: Check if package.json has "type": "module"
      - echo "Checking package.json contents:"
      - cat package.json | grep -A 2 '"type"'
  build:
    commands:
      - echo "BUILD PHASE STARTED"
      - docker build --no-cache -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "POST-BUILD PHASE STARTED"
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"recipe-finder-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json